import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';
await mkdir('lib', { recursive: true });
await mkdir('artifacts', { recursive: true });
await mkdir('companion/native-provider/lib', { recursive: true });
const host = (await readFile('src/index.mjs', 'utf8')).replace("'./protocol.mjs'", "'./protocol.js'").replace("'./ledger.mjs'", "'./ledger.js'").replace("'./connections.mjs'", "'./connections.js'").replace("'./routing.mjs'", "'./routing.js'").replace("'./acceptance.mjs'", "'./acceptance.js'").replace("'./coordination.mjs'", "'./coordination.js'").replace("'./program-checks.mjs'", "'./program-checks.js'").replace("'./deepseek-host.mjs'", "'./deepseek-host.js'").replace("'./chatgpt-host.mjs'", "'./chatgpt-host.js'").replace("'./chatgpt-router.mjs'", "'./chatgpt-router.js'").replace("'./deepseek-deadline.mjs'", "'./deepseek-deadline.js'").replace("'./research-acceptance.mjs'", "'./research-acceptance.js'").replace("'./research-contribution.mjs'", "'./research-contribution.js'");
await writeFile('lib/index.js', host.replace("'./subscription-reference.mjs'", "'./subscription-reference.js'"));
await writeFile('lib/subscription-reference.js', await readFile('src/subscription-reference.mjs', 'utf8'));
await writeFile('lib/ledger.js', (await readFile('src/ledger.mjs', 'utf8')).replace("'./subscription-reference.mjs'", "'./subscription-reference.js'"));
await writeFile('lib/connections.js', (await readFile('src/connections.mjs', 'utf8')).replace("'./native-connections.mjs'", "'./native-connections.js'").replace("'./subscription-reference.mjs'", "'./subscription-reference.js'"));
await writeFile('lib/native-connections.js', await readFile('src/native-connections.mjs', 'utf8'));
await writeFile('lib/routing.js', (await readFile('src/routing.mjs', 'utf8')).replace("'./ledger.mjs'", "'./ledger.js'").replace("'./connections.mjs'", "'./connections.js'"));
await writeFile('lib/acceptance.js', await readFile('src/acceptance.mjs', 'utf8'));
await writeFile('lib/coordination.js', await readFile('src/coordination.mjs', 'utf8'));
await writeFile('lib/program-checks.js', await readFile('src/program-checks.mjs', 'utf8'));
await writeFile('lib/deepseek-connections.js', (await readFile('src/deepseek-connections.mjs', 'utf8')).replace("'./deepseek-catalog.mjs'", "'./deepseek-catalog.js'"));
await writeFile('lib/deepseek-catalog.js', await readFile('src/deepseek-catalog.mjs', 'utf8'));
await writeFile('lib/deepseek-router.js', (await readFile('src/deepseek-router.mjs', 'utf8')).replace("'./deepseek-connections.mjs'", "'./deepseek-connections.js'"));
await writeFile('lib/deepseek-host.js', (await readFile('src/deepseek-host.mjs', 'utf8')).replace("'./deepseek-connections.mjs'", "'./deepseek-connections.js'").replace("'./deepseek-router.mjs'", "'./deepseek-router.js'"));
await writeFile('lib/deepseek-deadline.js', await readFile('src/deepseek-deadline.mjs', 'utf8'));
await writeFile('lib/chatgpt-oauth.js', (await readFile('src/chatgpt-oauth.mjs', 'utf8')).replace("'./source-network.mjs'", "'./source-network.js'"));
await writeFile('lib/chatgpt-responses.js', await readFile('src/chatgpt-responses.mjs', 'utf8'));
await writeFile('lib/chatgpt-router.js', (await readFile('src/chatgpt-router.mjs', 'utf8')).replace("'./chatgpt-responses.mjs'", "'./chatgpt-responses.js'"));
await writeFile('lib/chatgpt-sessions.js', (await readFile('src/chatgpt-sessions.mjs', 'utf8')).replace("'./chatgpt-oauth.mjs'", "'./chatgpt-oauth.js'"));
await writeFile('lib/chatgpt-host.js', (await readFile('src/chatgpt-host.mjs', 'utf8')).replace("'./chatgpt-oauth.mjs'", "'./chatgpt-oauth.js'").replace("'./source-network.mjs'", "'./source-network.js'").replace("'./chatgpt-sessions.mjs'", "'./chatgpt-sessions.js'"));
await writeFile('lib/research-artifact.js', await readFile('src/research-artifact.mjs', 'utf8'));
await writeFile('lib/research-acceptance.js', (await readFile('src/research-acceptance.mjs', 'utf8')).replace("'./research-artifact.mjs'", "'./research-artifact.js'").replace("'./source-network.mjs'", "'./source-network.js'"));
await writeFile('lib/source-network.js', await readFile('src/source-network.mjs', 'utf8'));
await writeFile('lib/research-contribution.js', (await readFile('src/research-contribution.mjs', 'utf8')).replace("'./research-artifact.mjs'", "'./research-artifact.js'"));
const protocol = await readFile('src/protocol.mjs', 'utf8');
await writeFile('lib/protocol.js', protocol);
await writeFile('lib/typert.host.js', "export { TYPERT, TYPERT as default } from './protocol.js';\n");
await writeFile('lib/typert.remote-client.js', "export { TYPERT_REMOTE, TYPERT_REMOTE as default } from './protocol.js';\n");
await writeFile('companion/native-provider/lib/index.js', await readFile('companion/native-provider/src/index.mjs', 'utf8'));
// Bundle the codec only. The host's ModuleLoader supplies React and the Cordis runtime.
const inline = protocol.replace("import { z } from 'zod';", '').replaceAll('export const ', 'const ');
const deepSeekClient = (await readFile('src/deepseek-client.mjs', 'utf8')).replaceAll('export function ', 'function ');
const chatGptClient = (await readFile('src/chatgpt-client.mjs', 'utf8')).replaceAll('export function ', 'function ');
const client = `${deepSeekClient}\n${chatGptClient}\n${await readFile('src/client.js', 'utf8')}`.replace('const descriptors = __ROUTER_REMOTE_DESCRIPTORS__;', `${inline}\nconst remoteDescriptors = descriptors;`).replace('package: \'@irishwei/dsh-router\', descriptors }),', 'package: \'@irishwei/dsh-router\', descriptors: remoteDescriptors }),');
await build({ stdin: { contents: `import { z } from 'zod';\n${client}`, resolveDir: process.cwd() }, outfile: 'lib/client.js', bundle: true, platform: 'browser', format: 'iife', target: 'es2022', minify: true });
